### ISSUE TITLE
Error (Elixir 1.11.0)

### ISSUE THREAD

**Issue by agramichael** [rcdilorenzo/filtrex#66]
Happening with all filters.

```
** (ArgumentError) argument error
        (stdlib 3.13) :ets.member(Mix.Compilers.ApplicationTracer, Ecto.Query)
        (mix 1.11.0) lib/mix/compilers/application_tracer.ex:31: Mix.Compilers.ApplicationTracer.trace/2
        (elixir 1.11.0) src/elixir_env.erl:36: :elixir_env."-trace/2-lc$^0/1-0-"/3
        (elixir 1.11.0) src/elixir_env.erl:36: :elixir_env.trace/2
        (elixir 1.11.0) src/elixir_dispatch.erl:189: :elixir_dispatch.expand_require/5
        (elixir 1.11.0) src/elixir_dispatch.erl:115: :elixir_dispatch.dispatch_require/6
        (elixir 1.11.0) src/elixir.erl:332: :elixir.quoted_to_erl/3 
        (elixir 1.11.0) src/elixir.erl:249: :elixir.eval_forms/3
        (elixir 1.11.0) lib/code.ex:700: Code.eval_quoted/3
        (filtrex 0.4.3) lib/filtrex.ex:115: Filtrex.query/3
```

**Comment by agramichael** [comment]
Fixed in Elixir 1.11.2 https://github.com/elixir-lang/elixir/commit/1bbc959d1a36ef09da080bdb8fbe0a2481981ce7
